export const SP_RANGE_TYPE_TO_FULL = {
  special: { text: 'Special' },
  point: { text: 'Point' },
  line: { text: 'Line' },
  cube: { text: 'Cube' },
  cone: { text: 'Cone' },
  radius: { text: 'Radius' },
  sphere: { text: 'Sphere' },
  hemisphere: { text: 'Hemisphere' },
  cylinder: { text: 'Cylinder' },
  self: { text: 'Self' },
  sight: { text: 'Sight' },
  unlimited: { text: 'Unlimited' },
  plane: { text: 'Unlimited on the same plane' },
  touch: { text: 'Touch' },
};
